defaults:
  - default_trainer

enable_model_summary: True
profiler: null

gradient_clip_val: 0
accumulate_grad_batches: 1
val_check_interval: 1.0
check_val_every_n_epoch: 1

log_every_n_steps: 1
num_sanity_val_steps: 2
fast_dev_run: False
overfit_batches: 1
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
detect_anomaly: True

precision: 32
accelerator: auto
num_nodes: 1